import Head from 'next/head'
import Headers from '../components/Headers'

export default function Home() {
  return (
    <div className='bg-stone-800 h-screen'>
      <Head>
        <title>Tashi Commercial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
    </div>
  )
}

